shiva/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site_app/', include('site_app.urls')),
    path('ticket_app/', include('ticket_app.urls')),
    path(r'', RedirectView.as_view(pattern_name='site_app:index')),


]

site_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

app_name = 'site_app'

ticket_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('list-tickets/', views.ListTickets.as_view(), name='list-tickets'),
    path('enable-ticket/<int:ticket_id>/', views.EnableTicket.as_view(), name='enable-ticket'),
    path('report-ticket/<int:ticket_id>/', views.ReportTicket.as_view(), name='report-ticket'),
    path('load-ticket/<int:ticket_id>/', views.LoadTicket.as_view(), name='load-ticket'),

    path('delete-ticket/<int:ticket_id>/<str:token>/', views.DeleteTicket.as_view(), name='delete-ticket'),
    path('ticket-matches/<int:ticket_id>/', views.TicketMatches.as_view(), name='ticket-matches'),
    path('create-ticket/', views.CreateTicket.as_view(), name='create-ticket'),
    path('find-ticket/', views.FindTicket.as_view(), name='find-ticket'),
    path('validate-email/<int:ticket_id>/<str:token>/', views.ValidateEmail.as_view(), name='validate-email'),
    path('avoid-expiration/<int:ticket_id>/<str:token>/', views.AvoidExpiration.as_view(), name='avoid-expiration'),

]

app_name = 'ticket_app'

site_app/models.py
from django.db import models

# Create your models here.

site_app/views.py
from django.shortcuts import render
from django.views.generic import View
from ticket_app.models import Ticket

# Create your views here.
class Index(View):
    def get(self, request):
        records = Ticket.objects.filter(enabled=True)
        count = records.count()

        return render(request, 
            'site_app/index.html', {'count': count})

site_app/templates/site_app/index.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Shiva</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>

<div class="jumbotron text-center">

<h3> 
<i class="fas fa-heart"> Shiva</i>
</h3>

<p> There are {{count}} tickets. 

<p>
<a href="{% url 'ticket_app:list-tickets' %}"> 
<i class="fas fa-hands-helping"> </i> Help?</a>

</div>

<div class="container">
<div class="row">
<div class="col-sm-3">
<h3>Food
</h3>
<p>Willing to share your bread? Create a ticket.</p>
</div>
<div class="col-sm-3">
<h3>Medical </h3>
<p>Can you help with medical resources? Create a ticket!</p>
</div>
<div class="col-sm-3">
<h3>Shelter</h3>        
<p>Are you a good host? Create a ticket!</p>
</div>
<div class="col-sm-3">
<h3>Utililities/Clothes</h3>        
<p>Need glasses, clothes? Create a ticket!</p>
</div>


</div>
</div>

</body>
</html>