shiva/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site_app/', include('site_app.urls')),
    path('ticket_app/', include('ticket_app.urls')),
    path(r'', RedirectView.as_view(pattern_name='site_app:index')),


]

ticket_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('list-tickets/', views.ListTickets.as_view(), name='list-tickets'),
    path('enable-ticket/<int:ticket_id>/', views.EnableTicket.as_view(), name='enable-ticket'),
    path('report-ticket/<int:ticket_id>/', views.ReportTicket.as_view(), name='report-ticket'),
    path('load-ticket/<int:ticket_id>/', views.LoadTicket.as_view(), name='load-ticket'),

    path('delete-ticket/<int:ticket_id>/<str:token>/', views.DeleteTicket.as_view(), name='delete-ticket'),
    path('ticket-matches/<int:ticket_id>/', views.TicketMatches.as_view(), name='ticket-matches'),
    path('create-ticket/', views.CreateTicket.as_view(), name='create-ticket'),
    path('find-ticket/', views.FindTicket.as_view(), name='find-ticket'),
    path('validate-email/<int:ticket_id>/<str:token>/', views.ValidateEmail.as_view(), name='validate-email'),
    path('avoid-expiration/<int:ticket_id>/<str:token>/', views.AvoidExpiration.as_view(), name='avoid-expiration'),

]

app_name = 'ticket_app'

ticket_app/models.py
from django.db import models
from django.db.models import Q
from urllib.parse import urljoin
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse

# from cities_light.models import City

# Create your models here.
class TicketMixin(models.Model):
    class Meta:
        abstract = True

    def __str__(self):
        return '%s - %s' % (self.name, self.email)

    @classmethod
    def find(cls, type=None, item_type=None, name=None, 
        phone=None, email=None, country=None, state=None, city=None,
        enabled=True, keywords=[]):

        records = cls.objects.filter(enabled=enabled)
        if city:
            records = records.filter(city__icontains=city)

        if type:
            records = records.filter(type=type)
        if item_type:
            records = records.filter(item_type=item_type)
        if name:
            records = records.filter(name__icontains=name)

        if phone:
            records = records.filter(phone=phone)

        if country:
            records = records.filter(country__icontains=country)

        if state:
            records = records.filter(state__icontains=state)

        if email:
            records = records.filter(email=email)

        qwords = Q()
        for ind in keywords:
            qwords = qwords | Q(note__icontains=ind)

        records = records.filter(qwords)
        return records

    def ticket_url(self):
        url = reverse('ticket_app:load-ticket', kwargs={
        'ticket_id': self.id})

        url = '%s%s' % (settings.SITE_ADDRESS, url)
        return url

    def ticket_matches(self):
        type = '0' if self.type == '1' else '1'
        query = Q(type=type, item_type=self.item_type,
        country=self.country, state=self.state, enabled=True)

        if self.city and self.type=='0':
            query = query & Q(city=self.city)

        records = self.__class__.objects.filter(query)
        return records

class TicketTokenMixin(models.Model):
    class Meta:
        abstract = True

    def delete_url(self):
        url = reverse('ticket_app:delete-ticket', kwargs={
        'ticket_id': self.ticket.id, 'token': self.token})
        url = '%s%s' % (settings.SITE_ADDRESS, url)

        return url

    def vmail_url(self):
        url = reverse('ticket_app:validate-email', kwargs={
        'ticket_id': self.ticket.id, 'token': self.token})
        url = '%s%s' % (settings.SITE_ADDRESS, url)

        return url

    def expiration_url(self):
        url = reverse('ticket_app:avoid-expiration', kwargs={
        'ticket_id': self.ticket.id, 'token': self.token})
        url = '%s%s' % (settings.SITE_ADDRESS, url)

        return url

    def send_token(self):
        url0 = self.vmail_url()
        url1 = self.delete_url()
        url2 = self.expiration_url()

        subject = 'Validate your Shiva ticket.'
        message = ('Click on the link to validate your ticket.\n%s\n\n'
        'Use this link to delete your ticket.\n%s\n\n'
        'Link to avoid ticket expiration on %s\n\n'
        'Your ticket will expire on %s\n')

        message = message % (url0, url1, 
        self.ticket.expiration, url2)

        recipient_list = [self.ticket.email,]

        send_mail(subject, message, settings.EMAIL_FROM, recipient_list)

class TicketReportMixin(models.Model):
    class Meta:
        abstract = True

class Ticket(TicketMixin):
    name = models.CharField(null=False,
    blank=False, verbose_name='Name', 
    help_text='Type your name.', max_length=256)

    phone = models.CharField(null=True,
    blank=True, verbose_name='Phone', 
    help_text='Type your phone.', max_length=30)

    email = models.EmailField(max_length=70, 
    verbose_name='E-mail', help_text='E-mail for contact.', 
    null=False, blank=False)

    TYPE_CHOICES = (('0', 'Need help!'),('1','Can help!'))

    type = models.CharField(max_length=6, 
    verbose_name='Type', help_text='Are you an angel?', 
    choices=TYPE_CHOICES, default='1')

    ITEM_TYPE_CHOICES = (('0', 'Food'), ('1','Medical'),
    ('2','Shelter'), ('3','Utils/Clothes'))

    item_type = models.CharField(max_length=6, 
    verbose_name='Item Type', choices=ITEM_TYPE_CHOICES, default='1',
    help_text='What is it that you have/need?')

    note = models.TextField(null=True,
    blank=False, verbose_name='Note', 
    help_text='Type a note.')

    # country = models.ForeignKey(Country, on_delete=models.CASCADE, default=None)
    # city = models.ForeignKey(City, verbose_name='Country/City', 
    # help_text='Where can you give/receive help?',
    # on_delete=models.CASCADE, default=None)

    country = models.CharField(null=False,
    blank=False, verbose_name='Country', 
    help_text='Type your country.', max_length=60)

    state = models.CharField(null=True,
    blank=False, verbose_name='State', 
    help_text='Type your state.', max_length=60)

    city = models.CharField(null=True,
    blank=True, help_text='Type your city. (Optional)', 
    max_length=60, verbose_name='City')

    alert_me = models.BooleanField(blank=False, 
    null=False, default=True, verbose_name='Notifications', 
    help_text='Get E-mail notifications for new tickets?',)

    expiration = models.DateTimeField(blank=True, null=False)

    created = models.DateTimeField(auto_now_add=True, null=True)
    enabled = models.BooleanField(default=False)

class TicketToken(TicketTokenMixin):
    token = models.CharField(null=False,
    blank=False, max_length=24)

    ticket = models.ForeignKey('Ticket', null=False, 
    related_name='token', on_delete=models.CASCADE)

class TicketReport(TicketReportMixin):
    reason = models.TextField(null=False,
    blank=False, verbose_name='Reason', 
    help_text='Type a reason.')

ticket_app/forms.py
from captcha.fields import ReCaptchaField
from ticket_app.models import Ticket, TicketReport
from django import forms
from django.conf import settings

class TicketForm(forms.ModelForm):
    # To get automated tests working. It seems ReCaptchaField doesn't
    # work as expected with required=False.

    captcha = forms.CharField(disabled=True, required=False,
    help_text='Google Captcha.') if settings.NOCAPTCHA \
    else ReCaptchaField() 

    class Meta:
        model   = Ticket
        exclude = ('enabled', )

class FindTicketForm(forms.Form):
    ITEM_TYPE_CHOICES = (('', '------'), ('0', 'Food'), 
    ('1','Medical'), ('2','Shelter'), ('3','Utils/Clothes'))

    TYPE_CHOICES = (('', '------'), ('0', 'Help'),('1','Helper'))

    keywords = forms.CharField(required=False, 
    help_text='Example: aspirins antibiotics')

    type = forms.ChoiceField(required=False, 
    choices=TYPE_CHOICES)

    item_type = forms.ChoiceField(required=False, 
    choices=ITEM_TYPE_CHOICES)

    country = forms.CharField(required=False, 
    help_text='Example: India')

    state = forms.CharField(required=False, 
    help_text='Example: RJ')

    city = forms.CharField(required=False, 
    help_text='Example: Rio')

    email = forms.EmailField(required=False, 
    help_text='Example: last.src@gmail.com')

class DeleteTicketForm(forms.Form):
    pass

class TicketReportForm(forms.ModelForm):
    class Meta:
        model   = TicketReport
        exclude = ()

ticket_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .models import TicketToken, Ticket
from django.core.mail import send_mail, mail_admins
from django.conf import settings
from datetime import date, timedelta
from . import forms
import secrets

# Create your views here.
class ListTickets(View):
    def get(self, request):
        tickets = Ticket.objects.filter(enabled=True)
        tickets = tickets.order_by('-created')

        return render(request, 
            'ticket_app/list-tickets.html', {'tickets': tickets})

class TicketMatches(View):
    def get(self, request, ticket_id):
        ticket  = Ticket.objects.get(id=ticket_id)
        matches = Ticket.ticket_matches(ticket)
        matches = matches.order_by('-created')

        return render(request, 
            'ticket_app/ticket-matches.html', {'matches': matches})

class EnableTicket(View):
    def get(self, request, ticket_id):
        ticket = Ticket.objects.get(id=ticket_id)

        c_helper = Ticket.objects.filter(type='1', enabled=True)
        c_help   = Ticket.objects.filter(type='0', enabled=True)
        c_helper = c_helper.count()
        c_help   = c_help.count()

        return render(request, 
            'ticket_app/enable-ticket.html', {'c_helper': c_helper, 
                'c_help': c_help, 'ticket': ticket})

class AvoidExpiration(View):
    def get(self, request, ticket_id, token):
        ticket = Ticket.objects.get(id=ticket_id)
        delta = timedelta(days=settings.TICKET_EXPIRATION)

        ticket.expiration = date.today() + delta
        ticket.save()

        return render(request, 
            'ticket_app/avoid-expiration.html', {'ticket': ticket})

class ValidateEmail(View):
    def get(self, request, ticket_id, token):
        token  = TicketToken.objects.get(token=token, ticket__id=ticket_id)
        token.ticket.enabled=True
        token.ticket.save()

        emails  = token.ticket.ticket_matches()
        emails  = emails.filter(alert_me=True)
        emails  = emails.distinct()
        emails  = emails.values_list('email', flat=True)
        url     = token.ticket.ticket_url()
        message = 'Check this new ticket!\n %s'
        subject = 'Shiva New Ticket!'

        message = message % url

        send_mail(subject, message, settings.EMAIL_FROM, emails)
        return render(request, 
            'ticket_app/validate-email.html', {'ticket': token.ticket})

class CreateTicket(View):
    def get(self, request):
        form = forms.TicketForm()
        return render(request, 
            'ticket_app/create-ticket.html', {'form': form})

    def post(self, request):
        form = forms.TicketForm(request.POST)

        if not form.is_valid():
            return render(request, 'ticket_app/create-ticket.html', 
                    {'form': form}, status=400)

        ticket = form.save(commit=False)
        delta  = timedelta(settings.TICKET_EXPIRATION)
        ticket.expiration = date.today() + delta
        ticket.save()

        token  = TicketToken.objects.create(
        token=secrets.token_urlsafe(24), ticket=ticket)

        token.send_token()
        return redirect('ticket_app:enable-ticket', 
        ticket_id=ticket.id)

class DeleteTicket(View):
    def get(self, request, ticket_id, token):
        token  = TicketToken.objects.get(token=token, ticket__id=ticket_id)

        return render(request, 'ticket_app/delete-ticket.html', 
            {'ticket': token.ticket, 'token': token.token})

    def post(self, request, ticket_id, token):
        form   = forms.DeleteTicketForm(request.POST)
        token  = TicketToken.objects.get(token=token, ticket__id=ticket_id)

        if not form.is_valid():
            return render(request, 'ticket_app/delete-ticket.html', 
                {'ticket': token.ticket, 'token': token.token})

        token.ticket.delete()
        return redirect('ticket_app:list-tickets')

class ReportTicket(View):
    def get(self, request, ticket_id):
        ticket = Ticket.objects.get(id=ticket_id)
        form   = forms.TicketReportForm(request.POST)

        return render(request, 'ticket_app/report-ticket.html', 
            {'ticket': ticket, 'form': form})


    def post(self, request, ticket_id):
        form   = forms.TicketReportForm(request.POST)
        ticket = Ticket.objects.get(id=ticket_id)

        if not form.is_valid():
            return render(request, 'ticket_app/report-ticket.html', 
                {'ticket': ticket, 'form': form})
        report = form.save()

        message = ('This ticket %s was reported.\n\n%s\n\n' 
        'Report ID: %s') % (ticket.ticket_url(), report.reason, report.id)

        mail_admins('Ticket Report.', message)
        return redirect('ticket_app:list-tickets')

class LoadTicket(View):
    def get(self, request, ticket_id):
        ticket = Ticket.objects.get(id=ticket_id)

        return render(request, 'ticket_app/load-ticket.html', 
            {'ticket': ticket})

# class CloseTicket(View):
    # def post(self, request):
        # pass

class FindTicket(View):
    def get(self, request):
        form = forms.FindTicketForm()

        return render(request, 
            'ticket_app/find-ticket.html', {'form': form})

    def post(self, request):
        form = forms.FindTicketForm(request.POST)

        if not form.is_valid():
            return render(request, 'ticket_app/find-ticket.html', 
                    {'form': form}, status=400)

        fields   = form.cleaned_data.items()
        fields   = dict(fields)
        keywords = fields.get('keywords') 

        fields['keywords'] = keywords.split(' ')
        records = Ticket.find(**fields)
        records = records.order_by('-created')

        return render(request, 
            'ticket_app/found-ticket.html', {'tickets': records})

ticket_app/templates/ticket_app/avoid-expiration.html
{% load i18n %}
<html lang="en">
<head>
  <title>Shiva</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>

<div class="jumbotron text-center">
  <h3><i class="fas fa-thumbs-up"></i> Ticket expiration !</h3> 
  <p> Your ticket expiration was extended !</p>

<a href="{% url 'ticket_app:list-tickets' %}"> <i class="fas fa-home"></i> Home </a>

</div>
  
<div class="container">
{% include 'ticket_app/ticket-model.html' with ticket=ticket %}

</div>

</body>
</html>

ticket_app/templates/ticket_app/create-ticket.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% load i18n %}
<html lang="en">
  <title>Shiva</title>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>

<div class="jumbotron text-center">
  <h3><i class="fas fa-heart"></i> New Ticket</h3> 

</div>
  
<div class="container">

<div class="panel panel-default">
<div class="panel-body">
<form action="{% url 'ticket_app:create-ticket' %}" method="post">
{% csrf_token %}

{% bootstrap_field form.name  size='md' %}
{% bootstrap_field form.email  size='md' %}
{% bootstrap_field form.phone  size='md' %}
{% bootstrap_field form.item_type  size='md' %}
{% bootstrap_field form.note  size='md' %}
{% bootstrap_field form.country  size='md' %}
{% bootstrap_field form.state  size='md' %}

{% bootstrap_field form.city  size='md' %}

<p> <b> Note:</b> 
New ticket notification from all state cities when city is blank.</p>

{% bootstrap_field form.type  size='md' %}

{% bootstrap_field form.alert_me  size='md' %}

{% bootstrap_field form.captcha  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}
<button type="submit" class="btn btn-success">Create</button>
</form>

</div>
</div>

</div>

</body>
</html>

ticket_app/templates/ticket_app/delete-ticket.html
{% load i18n %}
<html lang="en">
<head>
  <title>Shiva</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>

<div class="jumbotron text-center">
  <h3><i class="fas fa-thumbs-up"></i> Ticket Deletion !</h3> 
  <p> Are you sure you want to delete the ticket below? </p>

<form action="{% url 'ticket_app:delete-ticket' ticket.id token %}" method="post">
{% csrf_token %}

  <a href="{% url 'ticket_app:list-tickets' %}"> <i class="fas fa-home"></i> Back </a>
  <button type="submit" class="btn btn-link"><i class="fas fa-trash"></i> Delete</button>

</form>


</div>
<div class="container">
{% include 'ticket_app/ticket-model.html' with ticket=ticket %}

</div>

</body>
</html>

ticket_app/templates/ticket_app/find-ticket.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% load i18n %}
<html lang="en">
  <title>Shiva</title>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>

<div class="jumbotron text-center">
  <h3><i class="fas fa-search"></i> Find Tickets</h3> 
<a href="{% url 'ticket_app:list-tickets' %}"> <i class="fas fa-home"></i> Home </a>

</div>
  
<div class="container">
<p> <b> Note:</b> Search will be based on non blank fields  </p>

<div class="panel panel-default">
<div class="panel-body">
<form action="{% url 'ticket_app:find-ticket' %}" method="post">
{% csrf_token %}

{% bootstrap_field form.keywords  size='md' %}
{% bootstrap_field form.item_type  size='md' %}

{% bootstrap_field form.type  size='md' %}
{% bootstrap_field form.country  size='md' %}
{% bootstrap_field form.state  size='md' %}

{% bootstrap_field form.city  size='md' %}

{% bootstrap_field form.email  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}
<button type="submit" class="btn btn-success">Find</button>
</form>

</div>
</div>

</div>

</body>
</html>

ticket_app/templates/ticket_app/find-tickets.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% load i18n %}
<html lang="en">
  <title>Shiva</title>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>

<div class="jumbotron text-center">
  <h3><i class="fas fa-search"></i> Find Tickets</h3> 

</div>
  
<div class="container">

<div class="panel panel-default">
<div class="panel-body">
<form action="{% url 'ticket_app:create-ticket' %}" method="post">
{% csrf_token %}

{% bootstrap_field form.name  size='md' %}
{% bootstrap_field form.email  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}
<button type="submit" class="btn btn-success">Find</button>
</form>

</div>
</div>

</div>

</body>
</html>

ticket_app/templates/ticket_app/found-ticket.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shiva</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>

<div class="jumbotron text-center">
<h3>
<i class="fas fa-search"></i> Found tickets!
</h3> 
<a href="{% url 'ticket_app:find-ticket' %}"> <i class="fas fa-search"></i> Back/Find </a>

</div>
  
<div class="container">

{% for ind in tickets %}
{% include 'ticket_app/ticket-model.html' with ticket=ind %}
<br>
{% endfor %}
</div>

</body>
</html>

ticket_app/templates/ticket_app/list-tickets.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Shiva</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>

<div class="jumbotron text-center">
<h3><i class="fas fa-heart"></i> Available resources.</h3> 
<a href="{% url 'ticket_app:create-ticket' %}"> <i class="fas fa-heart"></i> Create </a>
<a href="{% url 'ticket_app:find-ticket' %}"> <i class="fas fa-search"></i> Find </a>


</div>

<div class="container">
{% for ind in tickets %}
{% include 'ticket_app/ticket-model.html' with ticket=ind %}
<br>
{% endfor %}
</div>

</body>
</html>

ticket_app/templates/ticket_app/report-ticket.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% load i18n %}
<html lang="en">
  <title>Shiva</title>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>

<div class="jumbotron text-center">
  <h3><i class="fas fa-heart-broken"></i> Report Ticket</h3> 

</div>
  
<div class="container">

<div class="panel panel-default">
<div class="panel-body">
<form action="{% url 'ticket_app:report-ticket' ticket.id %}" method="post">
{% csrf_token %}

{% bootstrap_field form.reason  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}
<button type="submit" class="btn btn-success">Report</button>
</form>

</div>
</div>

</div>

</body>
</html>

ticket_app/templates/ticket_app/ticket-model.html
<div class="card">
<div class="card-header">
<b> Author: </b>{{ticket.name}} (<a href="mailto: {{ticket.email}}"> {{ticket.email}}</a>)
<div class="float-right">
<a href="{% url 'ticket_app:report-ticket' ticket.id %}""> 
<i class="fas fa-heart-broken"></i>
Report </a>

<a href="{% url 'ticket_app:ticket-matches' ticket.id %}""> 
<i class="fas fa-search"></i>
Matches </a>
</div>

</div>

<p> <div class="card-body"><b>Item/Service:</b> {{ticket.get_item_type_display}} </p>

<p> <b> Phone:</b> {{ticket.phone}}  </p>

<p> <b> Note: </b> {{ticket.note}}  </p>

<p> <b> Country: </b> {{ticket.country}}  </p>

<p> <b> State: </b> {{ticket.state}}  </p>

<p> <b> City: </b> {{ticket.city}}  </p>


</div>
<div class="card-footer"><b> Type: </b>{{ticket.get_type_display}}
<div class="float-right"> <b> Created/Expiration: </b> 
{{ticket.created}} - {{ticket.expiration}} </div>

</div>
</div>